### ISSUE TITLE
Access-Control-Allow-Origin Problem

### ISSUE THREAD

**Issue by OZGURKISA** [jpedroh/ivao-whazzup#101]
Access to XMLHttpRequest at 'https://api.ivao.aero/getdata/whazzup/whazzup.txt' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

how can i solve this problem?

**Comment by jpedroh** [comment]
Hello @OZGURKISA.

This is a normal error that will be triggered when you try to use this library in a browser application, such as one built with React/Vue/Angular. This happens because IVAO API does not allow [CORS calls](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). 

Hence, you can only use this package in a server or in a command line application, since they do not need to use CORS requests;
